export const destinations = [
  {
    id: 1,
    name: "Ooty Lake",
    description: "A serene artificial lake surrounded by lush Eucalyptus trees, perfect for boating and lakeside walks.",
    image: "/images/dest_new_ooty_lake.png",
    distance: "2 km from city",
    rating: 4.8,
    reviews: 1240,
    tag: "Most Popular",
    duration: "2-3 hours",
  },
  {
    id: 2,
    name: "Doddabetta Peak",
    description: "The highest peak in the Nilgiris at 2,637m, offering panoramic views of the surrounding mountains.",
    image: "/images/dest_new_doddabetta.png",
    distance: "9 km from Ooty",
    rating: 4.9,
    reviews: 980,
    tag: "Must Visit",
    duration: "1-2 hours",
  },
  {
    id: 3,
    name: "Botanical Garden",
    description: "A magnificent 55-acre garden with over 650 plant species, established in 1848 on terraced hillsides.",
    image: "/images/dest_new_botanical.png",
    distance: "3 km from city",
    rating: 4.7,
    reviews: 1560,
    tag: "Heritage",
    duration: "2-3 hours",
  },
  {
    id: 4,
    name: "Tea Estates",
    description: "Sprawling emerald tea plantations offering guided tours, fresh tea tasting, and scenic walks.",
    image: "/images/dest_new_tea_estates.png",
    distance: "5 km from Ooty",
    rating: 4.8,
    reviews: 870,
    tag: "Experience",
    duration: "3-4 hours",
  },
  {
    id: 5,
    name: "Pykara Lake",
    description: "A pristine lake surrounded by shola forests, offering breathtaking beauty and a boat house.",
    image: "/images/dest_new_pykara.png",
    distance: "21 km from Ooty",
    rating: 4.6,
    reviews: 650,
    tag: "Nature",
    duration: "2-3 hours",
  },
  {
    id: 6,
    name: "Avalanche Lake",
    description: "A hidden gem at 2,400m altitude, a pristine blue lake with spectacular mountain views.",
    image: "/images/dest_new_avalanche.png",
    distance: "28 km from Ooty",
    rating: 4.9,
    reviews: 430,
    tag: "Hidden Gem",
    duration: "Half Day",
  },
  {
    id: 7,
    name: "Mudumalai Reserve",
    description: "A UNESCO World Heritage wildlife sanctuary home to tigers, elephants, leopards and rich flora.",
    image: "/images/dest_new_mudumalai.png",
    distance: "67 km from Ooty",
    rating: 4.8,
    reviews: 720,
    tag: "Wildlife",
    duration: "Full Day",
  },
  {
    id: 8,
    name: "Coonoor",
    description: "A charming hill station nestled at 1,858m with tea estates, colonial bungalows, and misty valleys.",
    image: "/images/dest_new_coonoor.png",
    distance: "19 km from Ooty",
    rating: 4.7,
    reviews: 1100,
    tag: "Hill Station",
    duration: "Full Day",
  },
];

export const tourPackages = [
  {
    id: 1,
    name: "Ooty Sightseeing Day Tour",
    description: "Explore all major Ooty attractions in a single day with an expert guide and premium vehicle.",
    highlights: ["Botanical Garden", "Doddabetta Peak", "Ooty Lake", "Rose Garden", "Tea Factory & Museum"],
    duration: "1 Day (10 hrs)",
    price: 1800,
    originalPrice: 2500,
    persons: "Up to 4",
    image: "/images/tour_ooty.jpg",
    badge: "Best Seller",
    badgeColor: "emerald",
    includes: ["Fuel & Driver Allowances", "Sightseeing Cab", "Parking & Tolls", "Free Bus Stand Pickup"],
  },
  {
    id: 2,
    name: "Ooty & Coonoor Combo Tour",
    description: "A complete experience covering the top highlights of both beautiful mountain towns.",
    highlights: ["Sim's Park Coonoor", "Valley View Point", "Lamb's Rock", "Ooty Lake", "Dolphin's Nose"],
    duration: "1 Day (12 hrs)",
    price: 2500,
    originalPrice: 3500,
    persons: "Up to 4",
    image: "/images/tour_train.jpg",
    badge: "Popular",
    badgeColor: "blue",
    includes: ["Fuel & Driver Allowances", "Sightseeing Cab", "Parking & Tolls", "Local Map Guide"],
  },
  {
    id: 3,
    name: "Honeymoon Special (Standard)",
    description: "Create beautiful memories with a highly romantic and private tour designed for couples.",
    highlights: ["Rose Garden Walk", "Private Boat Ride", "Sunset at Doddabetta", "Romantic Campfire Setup"],
    duration: "2 Days / 1 Night",
    price: 7000,
    originalPrice: 9500,
    persons: "2 Persons (Couple)",
    image: "/images/tour_doddabetta_view.jpg",
    badge: "Romantic",
    badgeColor: "rose",
    includes: ["Standard Hotel Stay", "Private Couple Cab", "Breakfast Included", "Surprise Floral Welcome"],
  },
  {
    id: 4,
    name: "Honeymoon Special (Luxury)",
    description: "An ultra-premium, all-inclusive luxury romantic getaway through Ooty's misty paradise.",
    highlights: ["Tea Estate Private Walk", "VIP Boat Cruise", "Luxury Valley View Resort", "Candlelight Dinner"],
    duration: "3 Days / 2 Nights",
    price: 13999,
    originalPrice: 18500,
    persons: "2 Persons (Couple)",
    image: "/images/stunning_tea_estate.png",
    badge: "Premium Luxury",
    badgeColor: "rose",
    includes: ["5-Star Resort Stay", "Private Luxury SUV", "All Meals & Decor", "Private Guide Assistance"],
  },
  {
    id: 5,
    name: "Friends & Family Group Package",
    description: "The perfect group package for friends or families traveling together. Fun, flexible, and affordable.",
    highlights: ["Mudumalai Safari", "Pykara Boat House", "Campfire with Music", "Trekking & Hiking Trails"],
    duration: "3 Days",
    price: 1500,
    originalPrice: 2200,
    persons: "Per Head (Min 6)",
    image: "/images/real_innova.jpg",
    badge: "Group Tour",
    badgeColor: "purple",
    includes: ["Comfortable Tempo Traveller", "Homestay Accommodation", "Driver Allowance & Taxes", "Local Hiking Guide"],
  },
  {
    id: 6,
    name: "Adventure & Wilderness Special",
    description: "An off-beat, thrilling adventure featuring private jungle jeep safaris and high-altitude trekking.",
    highlights: ["Avalanche Lake Permit", "Mudumalai Forest Safari", "Jungle Trekking", "Bison Valley View"],
    duration: "1 Day (12 hrs)",
    price: 1300,
    originalPrice: 1800,
    persons: "Per Head (Min 4)",
    image: "/images/real_mudumalai.jpg",
    badge: "Adventure",
    badgeColor: "orange",
    includes: ["4x4 Mountain Jeep", "Jungle Guide Fee", "Avalanche Entry Permits", "Packed Picnic Lunch"],
  },
  {
    id: 7,
    name: "Educational / Student Group Tour",
    description: "An educational and fun-filled expedition for schools, colleges, and academic groups.",
    highlights: ["Tea Museum Visit", "Botanical Garden Study", "Tribal Museum", "Safe & Guided Travel"],
    duration: "2 Days / 1 Night",
    price: 1800,
    originalPrice: 2500,
    persons: "Per Head (Min 20)",
    image: "/images/tour_stone_house.jpg",
    badge: "Educational",
    badgeColor: "green",
    includes: ["Premium Large Maxi Cabs", "Dormitory Group Stay", "All Meals (Veg)", "Industrial Entry Fees Included"],
  },
];

export const sightseeingCircuits = [
  {
    id: "ooty",
    name: "Ooty Local Sightseeing",
    places: "Doddabetta Peak, Tea Factory & Museum, Botanical Garden, Rose Garden, Wax Museum, Thread Garden, Ooty Lake, Shopping",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 1800, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 2200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 2500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 2800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 3500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 3600, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 4000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 4500, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 5000, capacity: "22+1" },
    ]
  },
  {
    id: "coonoor",
    name: "Coonoor Sightseeing Tour",
    places: "Valley View, MRC View, Sim's Park, Lamb's Rock, Dolphin's Nose, Tea Gardens, Shopping",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 1800, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 2200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 2500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 2800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 3500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 3500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 4200, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 5000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 5500, capacity: "22+1" },
    ]
  },
  {
    id: "pykara",
    name: "Pykara Scenic Tour",
    places: "Golf Club, 6th Mile Pine Forest, Wenlock Downs (Shooting Spot), Kamaraj Dam, Pykara Lake & Boating, Pykara Falls, Chocolate Museum",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 1800, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 2200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 2500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 2800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 3500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 3500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 4000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 5000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 5500, capacity: "22+1" },
    ]
  },
  {
    id: "mudumalai",
    name: "Mudumalai Wild Safari Tour",
    places: "Carnhill Forest, Bison Valley, Masinagudi, Mudumalai Tiger Reserve & Elephant Camp, Stephen's Church, Shopping",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 1800, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 2200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 2400, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 2800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 3500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 3500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 4000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 6000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 6500, capacity: "22+1" },
    ]
  },
  {
    id: "avalanche",
    name: "Avalanche Valley Explorer",
    places: "Avalanche Lake, Emerald Lake, Shola Forest Reserve Trails, Upper Bhavani Boundary (Permit Required), Trout Hatchery",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 1800, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 2200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 2500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 2800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 3500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 3500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 4000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 6000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 6500, capacity: "22+1" },
    ]
  },
  {
    id: "ooty_coonoor",
    name: "Ooty & Coonoor Mixed Tour",
    places: "Valley View, Sim's Park, Doddabetta Peak, Tea Factory & Museum, Botanical Garden, Ooty Lake",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 2500, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 3200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 3500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 3800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 4500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 4500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 5000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 7000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 7800, capacity: "22+1" },
    ]
  },
  {
    id: "ooty_pykara",
    name: "Ooty & Pykara Mixed Tour",
    places: "6th Mile Pine Forest, Wenlock Downs, Pykara Lake & Falls, Botanical Garden, Ooty Lake, Shopping",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 2500, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 3200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 3500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 3800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 4500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 4500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 5000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 7000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 7800, capacity: "22+1" },
    ]
  },
  {
    id: "pykara_mudumalai",
    name: "Pykara & Mudumalai Mixed Tour",
    places: "Pine Forest, Kamaraj Dam, Wenlock Downs, Masinagudi Valley, Mudumalai Tiger Reserve Safari Camp",
    rates: [
      { vehicle: "Hatchback (Indica)", price: 2500, capacity: "4+1" },
      { vehicle: "Hatchback Premium (Liva)", price: 3200, capacity: "4+1" },
      { vehicle: "Sedan (Indigo)", price: 3500, capacity: "4+1" },
      { vehicle: "Sedan Premium (Etios)", price: 3800, capacity: "4+1" },
      { vehicle: "SUV (Tavera)", price: 4500, capacity: "8+1" },
      { vehicle: "SUV Premium (Xylo)", price: 4500, capacity: "8+1" },
      { vehicle: "Luxury SUV (Innova)", price: 5000, capacity: "7+1" },
      { vehicle: "Tempo Traveller", price: 7000, capacity: "12+1" },
      { vehicle: "Maxi Cab", price: 7800, capacity: "22+1" },
    ]
  }
];

export const outstationTransfers = [
  {
    id: "cbe_airport",
    name: "Coimbatore Airport Transfer",
    distance: "90 km (3.5 hrs)",
    rates: { hatchback: 2200, sedan: 2500, suv: 3500, innova: 4400, tempo: 6500 }
  },
  {
    id: "cbe_station",
    name: "Coimbatore Railway Station Transfer",
    distance: "86 km (3 hrs)",
    rates: { hatchback: 2200, sedan: 2500, suv: 3500, innova: 4400, tempo: 6500 }
  },
  {
    id: "mtp_station",
    name: "Mettupalayam Railway Station Pickup/Drop",
    distance: "52 km (2 hrs)",
    rates: { hatchback: 1800, sedan: 2000, suv: 2800, innova: 3000, tempo: 4800 }
  },
  {
    id: "mysore_junction",
    name: "Mysore City / Railway Station Transfer",
    distance: "125 km (4 hrs)",
    rates: { hatchback: 4000, sedan: 4200, suv: 6000, innova: 7500, tempo: 10000 }
  },
  {
    id: "blr_airport",
    name: "Bangalore Kempegowda Airport Transfer",
    distance: "310 km (7.5 hrs)",
    rates: { hatchback: 7800, sedan: 8500, suv: 10000, innova: 13000, tempo: 18000 }
  },
  {
    id: "blr_city",
    name: "Bangalore City / Railway Station Transfer",
    distance: "275 km (6.5 hrs)",
    rates: { hatchback: 7500, sedan: 8000, suv: 10000, innova: 13000, tempo: 18000 }
  }
];

export const accommodationPackages = [
  {
    id: "budget_hotel",
    name: "Cozy Budget Stay",
    type: "Standard Hotel",
    price: 2499,
    originalPrice: 3500,
    highlights: ["Free WiFi", "Hot Water 24/7", "Close to Town Centre", "Clean & Hygienic Rooms"],
    image: "/images/stunning_tea_estate.png",
    rating: 4.5,
    reviews: 210,
    badge: "Great Value",
  },
  {
    id: "tea_cottage",
    name: "Premium Tea Valley Cottage",
    type: "Private Wooden Cottage",
    price: 4499,
    originalPrice: 6000,
    highlights: ["Misty Valley Balcony", "Campfire & BBQ Facility", "Local Homecooked Food", "Tea Plantation Walk"],
    image: "/images/stunning_tea_estate.png",
    rating: 4.8,
    reviews: 140,
    badge: "Highly Rated",
  },
  {
    id: "heritage_bungalow",
    name: "Heritage Colonial Estate Stay",
    type: "Historic British Bungalow",
    price: 6499,
    originalPrice: 9000,
    highlights: ["Fireplace in Room", "Antique Colonial Decor", "Private Garden", "Dedicated Butler Service"],
    image: "/images/stunning_panoramic_hero.png",
    rating: 4.9,
    reviews: 75,
    badge: "Heritage Experience",
  },
  {
    id: "luxury_resort",
    name: "Five-Star Luxury Resort",
    type: "Premium Hilltop Resort",
    price: 8999,
    originalPrice: 12500,
    highlights: ["Infinity Valley Pool", "Premium Spa & Wellness", "Fine Dining Restaurants", "Kid's Activity Zone"],
    image: "/images/real_hero.jpg",
    rating: 4.9,
    reviews: 110,
    badge: "Ultra Luxury",
  }
];

export const fleet = [
  {
    id: 1,
    name: "Hatchback",
    model: "Swift / i10",
    capacity: 4,
    luggage: "2 bags",
    ac: true,
    price: 12,
    features: ["Air Conditioned", "Music System", "GPS Tracked", "Clean & Sanitized"],
    icon: "🚗",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: 2,
    name: "Sedan",
    model: "Dzire / Aspire",
    capacity: 4,
    luggage: "3 bags",
    ac: true,
    price: 14,
    features: ["Air Conditioned", "Music System", "GPS Tracked", "Spacious Boot"],
    icon: "🚙",
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: 3,
    name: "SUV",
    model: "Ertiga / XL6",
    capacity: 6,
    luggage: "4 bags",
    ac: true,
    price: 18,
    features: ["Air Conditioned", "Music System", "GPS Tracked", "High Ground Clearance"],
    icon: "🚐",
    color: "from-emerald-500 to-green-600",
  },
  {
    id: 4,
    name: "Innova Crysta",
    model: "Toyota Innova 2.8",
    capacity: 7,
    luggage: "5 bags",
    ac: true,
    price: 22,
    features: ["Premium AC", "Captain Seats", "GPS Tracked", "Best for Mountains"],
    icon: "🏔️",
    color: "from-amber-500 to-orange-500",
    popular: true,
  },
  {
    id: 5,
    name: "Tempo Traveller",
    model: "Force Tempo 12-17 Seat",
    capacity: 17,
    luggage: "10 bags",
    ac: true,
    price: 35,
    features: ["Air Conditioned", "Push-back Seats", "GPS Tracked", "Ideal for Groups"],
    icon: "🚌",
    color: "from-violet-500 to-purple-600",
  },
  {
    id: 6,
    name: "Luxury SUV",
    model: "Fortuner / Scorpio N",
    capacity: 6,
    luggage: "4 bags",
    ac: true,
    price: 32,
    features: ["Premium AC", "Leather Seats", "GPS Tracked", "Sunroof Available"],
    icon: "✨",
    color: "from-rose-500 to-pink-600",
  },
];

export const testimonials = [
  {
    id: 1,
    name: "Priya Krishnamurthy",
    location: "Chennai",
    avatar: "PK",
    rating: 5,
    review: "Absolutely outstanding service! Our driver Rajan knew every hidden spot in the Nilgiris. The Innova was spotless and the journey was so comfortable. Nilgiris Explorers made our family vacation unforgettable!",
    package: "Ooty & Coonoor Tour",
    date: "March 2025",
    avatarBg: "from-rose-400 to-pink-500",
  },
  {
    id: 2,
    name: "Arjun Sharma",
    location: "Bangalore",
    avatar: "AS",
    rating: 5,
    review: "Booked the Honeymoon Special package and it exceeded all expectations. Every detail was perfect — the sunrise at Doddabetta, the private boat ride, the candlelight dinner setup. Truly magical!",
    package: "Honeymoon Special",
    date: "February 2025",
    avatarBg: "from-blue-400 to-indigo-500",
  },
  {
    id: 3,
    name: "Sarah Mitchell",
    location: "United Kingdom",
    avatar: "SM",
    rating: 5,
    review: "We came to Ooty as a group of 12 and the Tempo Traveller package was brilliant. Driver was punctual, vehicle was clean, and they arranged permits for Avalanche Lake which we couldn't have done ourselves.",
    package: "Avalanche Explorer",
    date: "January 2025",
    avatarBg: "from-emerald-400 to-green-500",
  },
  {
    id: 4,
    name: "Rajesh Venkataraman",
    location: "Hyderabad",
    avatar: "RV",
    rating: 5,
    review: "The wildlife safari at Mudumalai was incredible. Saw elephants, deer, and the driver positioned the vehicle perfectly. Fair pricing, no hidden charges. Will definitely use Nilgiris Explorers again!",
    package: "Mudumalai Wildlife",
    date: "April 2025",
    avatarBg: "from-amber-400 to-orange-500",
  },
  {
    id: 5,
    name: "Meera Nair",
    location: "Kochi",
    avatar: "MN",
    rating: 5,
    review: "Used them for airport transfer from Coimbatore to Ooty. Driver was waiting with a name board, helped with luggage, and the journey through the Ghat roads was smooth and safe. Very professional!",
    package: "Airport Transfer",
    date: "May 2025",
    avatarBg: "from-violet-400 to-purple-500",
  },
];

export const features = [
  {
    icon: "MapPin",
    title: "Expert Local Guides",
    description: "Our guides are Nilgiris natives — they know every hidden viewpoint, legend, and off-beaten trail.",
    gradient: "from-emerald-500 to-teal-600",
  },
  {
    icon: "Sparkles",
    title: "Curated Itineraries",
    description: "Every tour is expertly designed to balance iconic landmarks with secret local experiences.",
    gradient: "from-blue-500 to-indigo-600",
  },
  {
    icon: "Calendar",
    title: "Fully Flexible Plans",
    description: "Change your mind? No problem. Free rescheduling up to 24 hours before your trip.",
    gradient: "from-violet-500 to-purple-600",
  },
  {
    icon: "BadgeCheck",
    title: "Transparent Pricing",
    description: "No hidden charges, no commission. The quote we give is exactly what you pay.",
    gradient: "from-rose-500 to-pink-600",
  },
  {
    icon: "Users",
    title: "Group Specialists",
    description: "Family trips, honeymoons, corporate outings, school trips — we handle all group sizes perfectly.",
    gradient: "from-amber-500 to-orange-600",
  },
  {
    icon: "PhoneCall",
    title: "24/7 Concierge",
    description: "From booking to safe return, our travel concierge is reachable any hour of the day.",
    gradient: "from-cyan-500 to-blue-600",
  },
  {
    icon: "Shield",
    title: "Safe & Insured Travel",
    description: "All our vehicles are insured, sanitized, and driven by police-verified, experienced professionals.",
    gradient: "from-green-500 to-emerald-600",
  },
  {
    icon: "HeadphonesIcon",
    title: "Post-Trip Support",
    description: "Lost something? Need recommendations? Our team is available even after your trip ends.",
    gradient: "from-indigo-500 to-violet-600",
  },
];

export const galleryImages = [
  { src: "/images/real_hero.jpg", alt: "Nilgiris Mountain Landscape", cols: 2, rows: 2 },
  { src: "/images/stunning_toy_train.png", alt: "Historic Nilgiri Mountain Railway Toy Train", cols: 1, rows: 1 },
  { src: "/images/stunning_panoramic_hero.png", alt: "Panoramic View of Coonoor Hills", cols: 1, rows: 1 },
  { src: "/images/stunning_tea_estate.png", alt: "Emerald Tea Estate", cols: 1, rows: 1 },
  { src: "/images/stunning_ooty_lake.png", alt: "Boating at Ooty Lake", cols: 1, rows: 2 },
  { src: "/images/real_hero.jpg", alt: "Sunset over Nilgiris", cols: 2, rows: 1 },
  { src: "/images/stunning_pykara.png", alt: "Ancient Pykara Scenery", cols: 1, rows: 1 },
  { src: "/images/stunning_panoramic_hero.png", alt: "Misty Mountain Road", cols: 1, rows: 1 },
  { src: "/images/real_mudumalai.jpg", alt: "Mudumalai Wildlife Safari", cols: 1, rows: 1 },
  { src: "/images/stunning_botanical.png", alt: "Government Botanical Garden", cols: 1, rows: 1 },
];

export const stats = [
  { value: 10000, label: "Happy Travelers", suffix: "+" },
  { value: 2500, label: "Tours Completed", suffix: "+" },
  { value: 50, label: "Premium Vehicles", suffix: "+" },
  { value: 4.9, label: "Star Rating", suffix: "★", decimals: 1 },
];

export const steps = [
  {
    step: "01",
    title: "Share Your Vision",
    description: "Tell us your dream Nilgiris experience — destinations, dates, group size, and any special wishes.",
    icon: "Smartphone",
  },
  {
    step: "02",
    title: "Get a Free Itinerary",
    description: "Our travel experts craft a personalised day-by-day itinerary with pricing — within 2 hours.",
    icon: "Map",
  },
  {
    step: "03",
    title: "Confirm & Relax",
    description: "Approve the plan, make a simple payment, and let us handle every detail from here.",
    icon: "UserCheck",
  },
  {
    step: "04",
    title: "Experience The Magic",
    description: "Your guide and vehicle arrive on time. Explore iconic spots and secret gems with local expertise.",
    icon: "Car",
  },
  {
    step: "05",
    title: "Return With Memories",
    description: "Arrive back refreshed and happy. Share your story — and we'd love a review!",
    icon: "Home",
  },
];
